site_name: "ASCII Stuff"
repo_url: https://github.com/dhondta/asciistuff
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - ASCII objects: objects.md
  - ASCII file format: file.md
  - Helper functions: functions.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
